PeterAhern/CYF-FP-development-planner

package-lock.json
=> adjusting package-json

.gitignore, client/src/App.js, client/src/Components/Tasks/Tasks.js, client/src/Components/UI/Card/Card.js, client/src/pages/MyPlan.js, package-lock.json, package.json, server/api.js, server/db.js
=> Tasks mapping

client/src/Components/Tasks/Tasks.js
=> fixing fetch from front-end

client/src/App.js, client/src/Components/Header/Navbar/DropdownMenu.js, client/src/Components/TaskForm/TaskForm.js, client/src/Components/Tasks/Tasks.js, client/src/pages/GoogleAuth.css, client/src/pages/GoogleAuth.js, client/src/pages/Landing.css, client/src/pages/Landing.js, client/src/pages/MyPlan.js, package-lock.json, package.json, server/api.js
=> implemented google authentication and hooked it up

client/src/App.js, client/src/pages/GoogleAuth.js
=> fixing google authentication

client/src/Components/Element/Element.js, client/src/Components/TaskForm/TaskForm.js, client/src/Components/Tasks/Tasks.js, client/src/client.js, client/src/index.html, client/src/pages/GoogleAuth.js, client/src/pages/Landing.js, client/src/pages/MyPlan.js, package.json
=> bug fixes regarding post on render

client/src/index.html
=> Stylings for landing

client/src/index.html
=> Update index - heroku issue

server/app.js
=> another try

server/app.js
=> script-src-elem

package.json
=> proxy change

package-lock.json, server/app.js
=> added helmet with npm install and imported it, rookie mistake

server/app.js, server/middleware.js
=> adding the helmet to the middleware where it belongs

client/src/Components/Element/Element.js, client/src/Components/TaskForm/TaskForm.js, client/src/Components/Tasks/PopUpForm.css, client/src/Components/Tasks/PopUpForm.js, client/src/Components/Tasks/Tasks.js, server/api.js
Edit task functionality, edit task button, opens task form, can edit task details then update in db. the task list on the users page, automatically re-renders and updates to reflect changes of task details.
Fixes #1
- [x ] My code follows the style guidelines of this project
- [x ] I have carefully reviewed my own code
- [ x] I have commented my code
- [ x] I have updated any documentation
=> Edit tasks functionality working

package-lock.json
=> adding missing paclage-lock.json

client/src/Components/Element/Element.js, client/src/Components/Mentors/GraduateList/GraduateList.js, client/src/Components/Mentors/MentorsHome/MentorsHome.js, client/src/Components/Mentors/ViewAllGraduates/AllGraduates.js, server/api.js
=> graduate side 90% done

client/src/Components/Mentors/GraduateList/GraduateList.js, client/src/Components/Mentors/MentorsHome/MentorsHome.js, client/src/Components/Mentors/ViewAllGraduates/AllGraduates.js, client/src/Components/Mentors/ViewAllGraduates/MentorGraduates.js, server/api.js
Added 'Remove' button from graduates in graduate list, will remove the mentor/graduate connection and re-render graduate list component
Fixes #1
=> Graduate List - (remove graduate) functionality

client/src/Components/Graduates/GraduatesPlan/MyPlan.js, client/src/Components/Header/Navbar/Goal.js, client/src/Components/Header/Navbar/Navbar.js, client/src/pages/plan.js, server/api.js
Graduate goal now saves to database, and is saved in user table so that the information can be shown to mentors and saved between user sessions
Fixes #1
=> graduate goal now saves to db

client/src/Components/Tasks/Tasks.js, server/api.js
added a conditional check for data returned from api. If no tasks in db, a message is returned with success: true. Using this as a way to check if task list is empty on front end, so it will not populate the task cards with empty task data.
Fixes #1
=> fixed empty task cards appearing on a new user

client/src/Components/Mentors/GraduateList/Comment.js, server/api.js
=> Get notifications 

client/src/Components/Element/Element.js, client/src/Components/Mentors/GraduateList/Comment.js, client/src/Components/Mentors/GraduateList/GraduateElement.js, client/src/Components/Mentors/GraduateList/GraduateList.js, client/src/Components/Mentors/GraduateList/GraduateTasks.js, client/src/Components/Tasks/Tasks.js, server/api.js
Graduate can now view comments for specific element from mentor and from graduate previously.
Still need, to sort comments by date, newest first. Still need to fix date issue - each comments shows same date 27/03/22
Fixes #1
=> Comments Displayed - grad side

client/src/Components/Header/Navbar/DropdownMenu.js, client/src/Components/Mentors/GraduateList/Comment.js, client/src/Components/Mentors/MentorFeedback/Comment.js, server/api.js
=> Refresh to get the comments

client/src/Components/Mentors/GraduateList/Comment.js, client/src/Components/Mentors/MentorFeedback/Comment.js, client/src/Components/Mentors/MentorFeedback/GraduateElement.js, client/src/Components/Mentors/MentorFeedback/MentorsComment.js, client/src/Components/Mentors/MentorFeedback/Popup.css, server/api.js
=> Fixing the get errors

client/src/Components/Mentors/MentorFeedback/GraduateTasks.js, client/src/Components/Tasks/Tasks.js
Fixed the issue of fetching the grad tasks and displaying on the mentors side
Fixes #1
=> fixed grad tasks on mentor side

client/src/Components/TaskForm/TaskForm.js, client/src/Components/Tasks/Tasks.js
When editing task, the task form now prepopulates with correct due date and status, that can be edited and updated when submit the form.
Fixes #1
=> Edit task form populates correctly

client/src/Components/Tasks/Tasks.js
=> fixing the edit task functionality

client/src/Components/Element/Element.css, client/src/Components/Graduates/GraduatesPlan/MyPlan.css, client/src/Components/Mentors/MentorFeedback/GraduateElement.js
=> mentor can set tasks for a particular element for a graduate now

client/src/Components/Mentors/GraduateList/Comment.js, client/src/Components/TaskForm/PreloadedTasks.json, client/src/Components/TaskForm/TaskForm.js, client/src/Components/Tasks/Tasks.js
date issue fixed, now shows correct date
drop down, the options are not visible in the drop down, but they show on the text input, they are imported from JSON object of task examples. Datalist did not work so returned to select option. 
Fixes #1
=> date issue fixed (comments) & drop down options ongoing issue

client/src/Components/TaskForm/PreloadedTasks.json, client/src/Components/TaskForm/TaskForm.js
the drop down options now pull the correct data, corresponding to elementId from the JSON object
Fixes #1
=> fixed drop down options

client/src/Components/Graduates/GraduatesPlan/MyPlan.css, client/src/Components/Graduates/GraduatesPlan/MyPlan.js, client/src/Components/LandingComponents/landing.css, client/src/Components/Mentors/GraduateList/GraduateList.css, client/src/Components/Mentors/GraduateList/GraduateList.js, client/src/Components/Mentors/MentorFeedback/GraduateElement.js, client/src/Components/Mentors/MentorFeedback/MentorsComment.js, client/src/Components/Mentors/MentorFeedback/Popup.js, client/src/Components/Mentors/MentorsHome/MentorsHome.css, client/src/Components/Mentors/MentorsHome/MentorsHome.js, client/src/Components/Mentors/ViewAllGraduates/AllGraduates.css, client/src/Components/Mentors/ViewAllGraduates/AllGraduates.js
=> Mentors side/coding&styling

client/src/Components/Graduates/GraduatesPlan/MyPlan.js, client/src/Components/TaskForm/TaskForm.js, client/src/Components/Tasks/Tasks.js
Pop up task form automatically closes when submitting a new task, or when updating a task via edit task option
Fixes #1
=> pop ups close when submitting task form

client/src/Components/TaskForm/TaskForm.js, client/src/Components/Tasks/Tasks.js
=> removed unnecessary code

client/src/Components/Graduates/GraduatesPlan/MyPlan.js, client/src/Components/Graduates/GraduatesPlan/MyPlan.styles.js, client/src/Components/Header/Navbar/Goal.styles.js, client/src/Components/Header/Navbar/NavBar.styles.js, client/src/Components/Tasks/PopUpForm.js, client/src/Components/Tasks/Tasks.styles.js, client/src/Components/UI/Button/Button.js, client/src/index.css, client/src/pages/plan.js, client/src/pages/plan.styles.js
=> more designs for home page

client/src/App.js, client/src/Components/Header/Navbar/Navbar.js, client/src/Components/Mentors/MentorsHome/MentorsGuide.css, client/src/Components/Mentors/MentorsHome/MentorsGuide.js, client/src/pages/registration.styles.js
=> Mentors guide

client/src/Components/Mentors/GraduateList/Comment.js, client/src/Components/Mentors/GraduateList/GraduateList.js, client/src/Components/Mentors/GraduateList/GraduateList.styles.js, client/src/Components/Mentors/MentorFeedback/GraduateElement.js, client/src/Components/Mentors/MentorFeedback/MentorsComment.js, client/src/Components/Mentors/MentorFeedback/Popup.js, client/src/Components/Mentors/ViewAllGraduates/AllGraduates.js, server/api.js
=> Mentor home

client/src/Components/Mentors/ViewAllGraduates/AllGraduates.js
=> fixing the deploy craziness

client/src/Components/Mentors/MentorFeedback/MentorsComment.js, client/src/Components/Mentors/MentorFeedback/Popup.styles.js, client/src/Components/Mentors/MentorsHome/MentorsHome.styles.js, client/src/Components/Mentors/ViewAllGraduates/AllGraduates.js, client/src/Components/Mentors/ViewAllGraduates/AllGraduates.styles.js
=> mentorside-styling

client/src/Components/Graduates/GraduatesPlan/MyPlan.js, client/src/Components/Graduates/GraduatesPlan/MyPlan.styles.js, client/src/Components/Header/Navbar/NavBar.styles.js, client/src/Components/Header/Navbar/Navbar.js, client/src/Components/Tasks/Tasks.js, client/src/Components/Tasks/Tasks.styles.js
few small changes, any colours changed, I have left the old color in comments for comparing
Fixes #1
=> grad pain element section tweaks

client/src/Components/Mentors/MentorFeedback/GraduateTasks.js, client/src/Components/Mentors/MentorFeedback/GraduateTasks.styles.js, client/src/Components/Mentors/MentorFeedback/MentorsComment.js, client/src/Components/Mentors/MentorFeedback/MentorsComment.styles.js, client/src/Components/Mentors/MentorFeedback/Popup.styles.js, client/src/Components/Mentors/MentorsHome/MentorsHome.js, client/src/Components/Mentors/MentorsHome/MentorsHome.styles.js, client/src/Components/Mentors/ViewAllGraduates/AllGraduates.js, client/src/Components/Mentors/ViewAllGraduates/AllGraduates.styles.js, client/src/Components/Mentors/ViewAllGraduates/MentorGraduates.js, client/src/Components/Mentors/ViewAllGraduates/MentorGraduates.styles.js
=> Mentors design

client/src/Components/Graduates/GraduatesPlan/MyPlan.js, client/src/Components/Graduates/GraduatesPlan/MyPlan.styles.js, client/src/Components/TaskForm/PreloadedTasks.json, client/src/Components/TaskForm/TaskForm.js, client/src/Components/TaskForm/TaskForm.styles.js, client/src/Components/Tasks/PopUpForm.styles.js, client/src/Components/Tasks/Tasks.js, client/src/Components/Tasks/Tasks.styles.js, client/src/index.html
On element button, the number of task now is below, the elemend title. Other tweaks and improvements
Fixes #1
=> Grad page element section

client/src/Components/Header/Navbar/Navbar.js, client/src/Components/Mentors/MentorsHome/MentorsHome.js, client/src/Components/Tasks/PopupFeedBack.js
=> Popup for comments

client/src/Components/Graduates/GraduatesPlan/MyPlan.styles.js, client/src/Components/Tasks/PopUpForm.styles.js, client/src/Components/Tasks/Tasks.js, client/src/Components/Tasks/Tasks.styles.js, client/src/Components/UI/Button/Button.js
=> Grad mobile

client/src/Components/Mentors/MentorFeedback/GraduateTasks.js, client/src/Components/Mentors/MentorFeedback/GraduateTasks.styles.js, client/src/Components/Mentors/MentorsHome/MentorsHome.js, client/src/Components/Mentors/MentorsHome/MentorsHome.styles.js
=> Mentor side styling

client/src/Components/LandingComponents/Footer.styles.js, client/src/pages/registration.js, client/src/pages/registration.styles.js
=> landing page responsive

client/src/Components/LandingComponents/Footer.js, client/src/Components/LandingComponents/Footer.styles.js, client/src/pages/registration.styles.js
=> landing page logo improve

client/src/Components/Graduates/GraduatesPlan/MyPlan.js, client/src/Components/Mentors/MentorsHome/MentorsHome.js, client/src/Components/Mentors/MentorsHome/MentorsHome.styles.js, client/src/Components/Mentors/ViewAllGraduates/AllGraduates.styles.js, client/src/pages/registration.styles.js
=> mentor-mobile style ongoing

client/src/Components/Graduates/GraduatesPlan/MyPlan.js, client/src/Components/LandingComponents/Footer.styles.js, client/src/Components/Mentors/MentorFeedback/MentorsComment.js, client/src/Components/Mentors/MentorsHome/MentorsHome.js, client/src/Components/Mentors/MentorsHome/MentorsHome.styles.js, client/src/Components/Mentors/ViewAllGraduates/AllGraduates.styles.js, client/src/Components/Mentors/ViewAllGraduates/MentorGraduates.js, client/src/Components/Mentors/ViewAllGraduates/MentorGraduates.styles.js
=> stylings to match grad side - ongoing

client/src/Components/Mentors/MentorFeedback/GraduateTasks.js, client/src/Components/Mentors/MentorFeedback/GraduateTasks.styles.js, client/src/Components/Mentors/MentorsHome/MentorsHome.js, client/src/Components/Mentors/MentorsHome/MentorsHome.styles.js
=> mentorside stylings - buttons

client/src/Components/Header/Navbar/NavBar.styles.js, client/src/Components/Header/Navbar/Navbar.js
=> mentorguide button moved

client/src/Components/Mentors/ViewAllGraduates/MentorGraduates.js, client/src/Components/Mentors/ViewAllGraduates/MentorGraduates.styles.js, client/src/index.html, client/src/index.js, client/src/pages/MentorsGuide.js, client/src/pages/MentorsGuide.styles.js
=> Final things

client/src/Components/Header/Navbar/Navbar.js, client/src/Components/LandingComponents/Login.js, client/src/Components/LandingComponents/landingComponents.js, client/src/pages/plan.js, client/src/pages/plan.styles.js, client/src/pages/registration.js, client/src/pages/registration.styles.js, package-lock.json
=> Mentors mobile

client/src/Components/Mentors/MentorFeedback/MentorsComment.js, client/src/Components/Mentors/MentorFeedback/MentorsComment.styles.js, client/src/Components/Tasks/PopUpForm.styles.js
=> Comments pop up

client/src/Components/Mentors/MentorsHome/MentorsHome.js
=> fixing the initial empty task displayed for mentors

client/src/Components/Graduates/GraduatesPlan/MyPlan.js, client/src/Components/Header/Navbar/Navbar.js, client/src/Components/Mentors/MentorsHome/MentorsHome.js
=> Navbar links

client/src/Components/Mentors/MentorFeedback/GraduateElement.styles.js, client/src/Components/Mentors/MentorsHome/MentorsHome.js, client/src/Components/Mentors/MentorsHome/MentorsHome.styles.js, client/src/Components/Tasks/PopUpForm.styles.js
=> Mentor page - comment box color changed

client/src/Components/Header/Navbar/Navbar.js, client/src/Components/Mentors/MentorsHome/MentorsHome.js, client/src/Components/Mentors/MentorsHome/MentorsHome.styles.js
=> Using use effect

client/src/Components/Mentors/MentorsHome/MentorsHome.js, server/api.js
=> back-end improved
